# baseURL = "http://localhost:1313/"
baseURL = "blog.babage.eu.org"
languageCode = "zh-cn"
title = "boba博客"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime  = true
  ShowShareButtons = true
  ShowPostNavLinks = true

  # 如果你不想在本地/预览和生产环境来回修改 baseURL
  relativeURLs = true
  canonifyURLs = false




  